automation:
  enabled: true
  name: youtube_trending_intelligence_enrichment_daily
  triggers:
    sensors:
      - type: timer
        name: daily-midnight-utc-youtube-enrichment
        config:
          schedule:
            cron: '0 0 * * *'
  actions:
    - type: run_flow
      name: run-youtube-trending-intelligence-enrichment-daily
      config:
        flow: youtube_trending_intelligence
        components:
          - read_youtube_video_enrichment